jusleg/soen341

README.md

Added my name to the list & changed soen341 to SOEN 341

Updated the readme for #3

---

README.md

Eric PR to ReadMe

---

README.md

Make Initial Pull request onto Master branch. 
*Add name in README

Make Initial Pull request 

---

README.md

Added Steven Ha into readme file

Modified Readme to add Steven Ha

---

.gitignore

idea/
*.keystore
*.sw*
.DS_Store
._*
Thumbs.db
.cache
*.sublime-project
*.sublime-workspace
TODO.md
.sass-cache
node_modules
bower_components
build
/tmp
Added to gitIgnore

git ignore added to master 

---

.gitignore

 corrected git ignore

---

.gitignore
package.json

Added Express and body-parser
Also changed gitignore.

backend dependencies

---

app.js
routes/index.js
routes/login.js

add 'routes' folder

---

bower.json

added angular dependencies

---

README.md

Move the instructions to the wiki since everything is explained thoroughly there.

Added wiki link in the readme

---

bower.json
public/app/app.html
public/css/mainStyle.css
public/css/nav.css
public/scss/mainStyle.scss
public/scss/nav.scss

added header to layout #23

---

public/app/app.html
public/css/classroom.css
public/css/mainStyle.css
public/scss/classroom.scss
public/scss/mainStyle.scss
public/scss/sideBar.scss
public/views/classroom.html

Now has a shadow which will cover the content when the SideBar is active in mobile.
Content will scroll away from SideBar when Side bar is Open in Mobile.

Improved mobile responsiveness

---

public/css/landing.css
public/css/mainStyle.css
public/scss/landing.scss
public/scss/mainStyle.scss
public/views/landing.html

Only thing missing is the link to the sign up page and the link to the
sign in page. It should be added once we have them

Landing page created #68

---

public/views/landing.html

@miisaka  Dont route it by passing it the website's url. We're routing using Node and Angular.

Changed routing 

---

public/app/app.html
public/css/mainStyle.css
public/css/sideBar.css
public/scss/sideBar.scss

changed and improved nav bar design with better syntax and structure

reformated navbar design- sideBar.css

---

public/css/classroom.css
public/css/mainStyle.css
public/scss/classroom.scss
public/views/classroom.html

The ul element should not have a div as it's child element.

refacted the message in the UL

---

app/routes/routes.js
config/passport.js
public/javascript/register.js

@izconcept fixed the routing to the main chat application

Login registration fix

---

public/app/app.html

changed col-sm-2 to col-sm-3 to have a total of: 12 instead of 11.

fixed div class to be correctly responsive

---

public/css/classroom.css
public/css/mainStyle.css
public/scss/classroom.scss

Messages can now be completely seen in the chat box

fixed issue with message display in chat box 0.1 hours

---

public/css/classroom.css
public/css/mainStyle.css
public/scss/classroom.scss

Revert "fixed issue with message display in chat box 0.1 hours"

---

public/css/register.css
public/scss/register.scss

I downloaded the image that was not being displayed on the signup page and hosted it on imgur. I modified the css and scss to include the new link.
#107

Fix register email icon

---

app/routes/routes.js
public/css/pass-change.css
public/javascript/pass-change.js
public/scss/pass-change.scss
public/views/pass-change.html

-Added password reset page
-Styled password reset page
-Added front end password validation
-Setup temporary route '/resetPassword' pending implementation of AES link generation

Password change page #64

---

app/routes/routes.js
config/passport.js
index.js
public/app/app.html

-Implemented sessions
-Implemented log out feature
-The chat route is now secured, can only be accessed by login in
-Added error message if users try to access a non configured route (404 not found)
-Added error message if user try to access the chat route without login in

Session fix #90

---

app/routes/api.js
index.js

Had to change the order of routing files so that get("*") does not override api calls

fixed api routing #112

---

wiki/burndown.md
wiki/database_documentation.md
wiki/home.md
wiki/meeting_notes.md
wiki/scrum_meetings.md

Created documentation to source code.
**Estimated Hours:** 0.25h
**Story point:** 1

Documentation

---

public/javascript/classroom.controller.js

Users no longer can send empty messages to spam #115

---

wiki/meeting_notes.md

Updates the meeting notes in wiki and moved it to documentation source

Added Meeting 4 and 5

---

app/aes.js

AES module usage:
```
const aes = require('./app/aes.js');
aes.encrypt(aes.encrypt("msgToEncrypt"));
// ex return value: U2FsdGVkX18ZUVvShFSES21qHsQEqZXMxQ9zgHy+bu0=
aes.encrypt(aes.decrypt("encryptedMsg"));
// returns original message
```

#67 Added aes-256 encryption module (which passed basic local tests)

---

wiki/burndown.md
wiki/scrum_meetings.md

More documentation

---

Test/test.js
app/routes/api.js
app/routes/routes.js
index.js

-Added a route to access the currently logged in user's information
-Also moved the "Online" boolean to be stored inside the user's session instead of inside the database

#131 user info

---

public/app.js
public/javascript/classroom.controller.js

Hot fix where two people couldnt chat together LIVE

---

Test/test.js
app/routes/api.js
app/routes/routes.js
index.js
public/app.js
public/app/app.html
public/javascript/classroom.controller.js
public/javascript/header.controller.js

Frontend #116

---

public/app.js
public/app/app.html
public/javascript/classroom.controller.js
public/javascript/header.controller.js

current user information displayed properly and on chat box

---

public/views/login.html

Some of the changes I made where left out of the git tree. Because michel pushed some files ahead of mine, it is impossible for me to commit anterior versions. This file wasn't part of the original forgotPass branch merge #145 so this pr is to add it to develop. #64

Recommit of login.html

---

wiki/meeting_notes.md

added meeting notes #6

---

app/models/Classes.js
app/models/user.js
app/routes/file-upload.js
public/app.js
public/app/app.html
public/css/mainStyle.css
public/javascript/createclass.controller.js
public/javascript/createclass.js
public/javascript/modules/createclass.module.js
public/scss/register.scss
public/views/create-class.html

Schema incompatibility resolved, backend refactored, UI improved and added into main app.

Create class #135: Better integration with main app.

---

public/views/create-class.html

#135 Small change to fix Cancel button on Create Class form

---

app/models/user.js
config/passport.js

-Modif on user model to include imglink (will be used as the profile
img src)
-Modif on passport.js signup to add imglink as a field
The email of the user is hash using md5 and we do a request on
gravatar.com for the latest picture. If no picture is found, a randomly
generated picture will be displayed.

Autogenerate gravatar link on sign up (1h)

---

public/app/app.html
public/css/mainStyle.css
public/scss/register.scss
public/views/register.html

added teacher message on registration page

---

app/models/Classes.js
app/routes/file-upload.js

#169 Added Mongoose timestamp setting to Classes schema; class creation now records creation time and update time.

#169: Class creation date stored in db

---

app/routes/routes.js
public/views/landing.html

-swal2 added
-redirect with params added
-param scrapper added in landing.html

Added message support for landing page

---

app/routes/routes.js
public/views/landing.html
public/views/login.html

notification on wrong password + 404

---

index.js

Added session timeout after 15min

---

app/routes/api.js

Added api route to retrieve total amount of online users

Online in class #92

---

public/app/app.html
public/javascript/classroom.controller.js
public/views/login.html

 added logger for info when events occur

---

app/routes/routes.js
public/views/register.html

Added warning message when registering an existing email

---

app/models/user.js
app/routes/routes.js
config/passport.js

-Added login validation to check if the user's account has been validated

Added login check for validated users

---

app/routes/routes.js
config/passport.js
index.js
package.json
public/views/login.html

added req.flash 
fix small parenthesis mistake of @miisaka :wink:
swal alert
paramScrape on login

Account validation message

---

public/app/app.html
public/javascript/classroom.controller.js
public/javascript/createclass.controller.js

logs error if creating a class doesn't work

---

app/routes/routes.js
config/passport.js
public/views/login.html

Removed redirect upon registration and added instructions

---

public/app/app.html
public/javascript/createclass.controller.js

tmeporary section for calss mod and class user

---

app/routes/email.js
app/routes/routes.js
config/passport.js
public/views/login.html

Added reverify-email

---

app/routes/routes.js
package.json

-Added a cron job to switch boolean in db to false when user's session expires

Fixed online boolean bug

---

public/javascript/createclass.controller.js

replaced regex with a more accurate one for class code #196

---

public/app.js
public/app/app.html
public/css/mainStyle.css
public/javascript/classroom.controller.js
public/views/classroom.html

Page now shows how many people are online
hours:1
#92

Show number of users online

---

public/app.js
public/app/app.html
public/css/mainStyle.css
public/scss/classroom.scss
public/scss/mainStyle.scss
public/scss/sideBar.scss

Navbar update

---

public/app/app.html

Added branding to our app

---

public/app/app.html
public/views/homepage.html
public/views/landing.html
public/views/login.html
public/views/pass-change.html
public/views/register.html

Removed unnecessary empty lines of code
Time: 30 minutes

Code cleanup #167

---

app/routes/file-upload.js
public/javascript/createclass.controller.js

#201 Prevents teachers from creating duplicate classes; bug is fixed, and proper error message is shown if they attempt to do this.

Duplicate name fix from master
